const fs = require('fs');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');

const rawQuestions = [
  {
    num: 1,
    q: "What was Mahatma Gandhi's full name?",
    q_ml: "മഹാത്മാഗാന്ധിയുടെ പൂർണ്ണനാമം എന്തായിരുന്നു?",
    a: "Mohandas Karamchand Gandhi",
    a_ml: "മോഹൻദാസ് കരംചന്ദ് ഗാന്ധി",
    b: "Mohanlal Karamchand Gandhi",
    b_ml: "മോഹൻലാൽ കരംചന്ദ് ഗാന്ധി",
    c: "Mohandas Kasturba Gandhi",
    c_ml: "മോഹൻദാസ് കസ്തൂർബ ഗാന്ധി",
    d: "Karamchand Mohandas Gandhi",
    d_ml: "കരംചന്ദ് മോഹൻദാസ് ഗാന്ധി",
    correct: "A",
    category: "Early Life & Family"
  },
  {
    num: 2,
    q: "Gandhi was born on:",
    q_ml: "ഗാന്ധിജി ജനിച്ച തീയതി ഏതാണ്?",
    a: "2 October 1869",
    a_ml: "1869 ഒക്ടോബർ 2",
    b: "2 October 1870",
    b_ml: "1870 ഒക്ടോബർ 2",
    c: "9 January 1869",
    c_ml: "1869 ജനുവരി 9",
    d: "30 January 1869",
    d_ml: "1869 ജനുവരി 30",
    correct: "A",
    category: "Early Life & Family"
  },
  {
    num: 3,
    q: "Which place is identified as Gandhi's birthplace in the module?",
    q_ml: "പഠനസഹായി പ്രകാരം ഗാന്ധിജിയുടെ ജന്മസ്ഥലം ഏതാണ്?",
    a: "Rajkot",
    a_ml: "രാജ്കോട്ട്",
    b: "Porbandar",
    b_ml: "പോർബന്ദർ",
    c: "Ahmedabad",
    c_ml: "അഹമ്മദാബാദ്",
    d: "Bombay",
    d_ml: "ബോംബെ",
    correct: "B",
    category: "Early Life & Family"
  },
  {
    num: 4,
    q: "Gandhi's birthplace in Porbandar is now known as:",
    q_ml: "പോർബന്ദറിലെ ഗാന്ധിജിയുടെ ജന്മസ്ഥലം ഇപ്പോൾ അറിയപ്പെടുന്നത്:",
    a: "Gandhi Bhavan",
    a_ml: "ഗാന്ധി ഭവൻ",
    b: "Gandhi Smriti",
    b_ml: "ഗാന്ധി സ്മൃതി",
    c: "Kirti Mandir",
    c_ml: "കീർത്തി മന്ദിർ",
    d: "Sabarmati Ashram",
    d_ml: "സബർമതി ആശ്രമം",
    correct: "C",
    category: "Early Life & Heritage"
  },
  {
    num: 5,
    q: "Who was Gandhi's father?",
    q_ml: "ഗാന്ധിജിയുടെ പിതാവ് ആരായിരുന്നു?",
    a: "Gopal Krishna Gokhale",
    a_ml: "ഗോപാലകൃഷ്ണ ഗോഖലെ",
    b: "Karamchand Gandhi",
    b_ml: "കരംചന്ദ് ഗാന്ധി",
    c: "Mahadev Desai",
    c_ml: "മഹാദേവ് ദേശായി",
    d: "Vallabhbhai Patel",
    d_ml: "വല്ലഭ്ഭായ് പട്ടേൽ",
    correct: "B",
    category: "Early Life & Family"
  },
  {
    num: 6,
    q: "Which school did Gandhi attend in Rajkot?",
    q_ml: "രാജ്കോട്ടിൽ ഗാന്ധിജി പഠിച്ച വിദ്യാലയം ഏതാണ്?",
    a: "Alfred High School",
    a_ml: "ആൽഫ്രഡ് ഹൈസ്കൂൾ",
    b: "Shyamaldas College",
    b_ml: "ശ്യാമൾദാസ് കോളേജ്",
    c: "Inner Temple",
    c_ml: "ഇന്നർ ടെമ്പിൾ",
    d: "Gujarat College",
    d_ml: "ഗുജറാത്ത് കോളേജ്",
    correct: "A",
    category: "Education"
  },
  {
    num: 7,
    q: "Where did Gandhi obtain his legal qualification in London?",
    q_ml: "ലണ്ടനിൽ ഗാന്ധിജി നിയമബിരുദം (ബാരിസ്റ്റർ) നേടിയത് എവിടെ നിന്നാണ്?",
    a: "Oxford",
    a_ml: "ഓക്സ്ഫോർഡ്",
    b: "Cambridge",
    b_ml: "കേംബ്രിഡ്ജ്",
    c: "Inner Temple",
    c_ml: "ഇന്നർ ടെമ്പിൾ",
    d: "London School of Law",
    d_ml: "ലണ്ടൻ സ്കൂൾ ഓഫ് ലോ",
    correct: "C",
    category: "Education"
  },
  {
    num: 8,
    q: "During his time in London, Gandhi became a member of the:",
    q_ml: "ലണ്ടനിലെ താമസകാലത്ത് ഗാന്ധിജി താഴെ പറയുന്ന ഏതിലാണ് അംഗമായത്?",
    a: "Indian National Congress",
    a_ml: "ഇന്ത്യൻ നാഷണൽ കോൺഗ്രസ്",
    b: "Vegetarian Society",
    b_ml: "വെജിറ്റേറിയൻ സൊസൈറ്റി",
    c: "Natal Indian Congress",
    c_ml: "നറ്റാൽ ഇന്ത്യൻ കോൺഗ്രസ്",
    d: "Young India Society",
    d_ml: "യംഗ് ഇന്ത്യ സൊസൈറ്റി",
    correct: "B",
    category: "Education & London Years"
  },
  {
    num: 9,
    q: "Why did Gandhi initially travel to South Africa in 1893?",
    q_ml: "1893-ൽ ഗാന്ധിജി ആദ്യമായി ദക്ഷിണാഫ്രിക്കയിലേക്ക് പോയതിന്റെ പ്രധാന കാരണം എന്തായിരുന്നു?",
    a: "To establish an ashram",
    a_ml: "ആശ്രമം സ്ഥാപിക്കാൻ",
    b: "To study law",
    b_ml: "നിയമപഠനത്തിനായി",
    c: "To argue a case for Dada Abdulla",
    c_ml: "ദാദാ അബ്ദുള്ളയുടെ കേസ് വാദിക്കാൻ",
    d: "To lead a political movement",
    d_ml: "രാഷ്ട്രീയ പ്രസ്ഥാനത്തിന് നേതൃത്വം നൽകാൻ",
    correct: "C",
    category: "South Africa Years"
  },
  {
    num: 10,
    q: "The Pietermaritzburg incident occurred in:",
    q_ml: "പീറ്റർമാരിറ്റ്സ്ബർഗ് സംഭവം നടന്ന വർഷം ഏതാണ്?",
    a: "1888",
    a_ml: "1888",
    b: "1893",
    b_ml: "1893",
    c: "1906",
    c_ml: "1906",
    d: "1915",
    d_ml: "1915",
    correct: "B",
    category: "South Africa Years"
  },
  {
    num: 11,
    q: "What happened to Gandhi at Pietermaritzburg?",
    q_ml: "പീറ്റർമാരിറ്റ്സ്ബർഗിൽ വെച്ച് ഗാന്ധിജിക്ക് നേരിടേണ്ടി വന്ന അനുഭവം എന്തായിരുന്നു?",
    a: "He was arrested for protesting",
    a_ml: "പ്രതിഷേധിച്ചതിന് അറസ്റ്റ് ചെയ്യപ്പെട്ടു",
    b: "He was removed from a train because of racial discrimination",
    b_ml: "വംശീയ വിവേചനം കാരണം ട്രെയിനിൽ നിന്ന് പുറത്താക്കപ്പെട്ടു",
    c: "His law practice was closed",
    c_ml: "അദ്ദേഹത്തിന്റെ നിയമ പരിശീലനം നിർത്തിവെപ്പിച്ചു",
    d: "He was imprisoned for refusing tax",
    d_ml: "നികുതി നൽകാത്തതിന് ജയിലിലടയ്ക്കപ്പെട്ടു",
    correct: "B",
    category: "South Africa Years"
  },
  {
    num: 12,
    q: "The Natal Indian Congress was established in:",
    q_ml: "നറ്റാൽ ഇന്ത്യൻ കോൺഗ്രസ് സ്ഥാപിക്കപ്പെട്ട വർഷം ഏതാണ്?",
    a: "1893",
    a_ml: "1893",
    b: "1894",
    b_ml: "1894",
    c: "1903",
    c_ml: "1903",
    d: "1906",
    d_ml: "1906",
    correct: "B",
    category: "South Africa Years"
  },
  {
    num: 13,
    q: "The first use of the term/practice of Satyagraha mentioned in the module occurred in:",
    q_ml: "പഠനസഹായി പ്രകാരം ആദ്യമായി സത്യാഗ്രഹം പ്രയോഗിച്ച വർഷം ഏതാണ്?",
    a: "1894",
    a_ml: "1894",
    b: "1903",
    b_ml: "1903",
    c: "1906",
    c_ml: "1906",
    d: "1915",
    d_ml: "1915",
    correct: "C",
    category: "Satyagraha"
  },
  {
    num: 14,
    q: "Against which law was Gandhi's first Satyagraha in South Africa organised?",
    q_ml: "ദക്ഷിണാഫ്രിക്കയിൽ ഗാന്ധിജിയുടെ ആദ്യ സത്യാഗ്രഹം ഏത് നിയമത്തിനെതിരെയായിരുന്നു?",
    a: "Rowlatt Act",
    a_ml: "റൗലറ്റ് ആക്ട്",
    b: "Salt Act",
    b_ml: "സാൾട്ട് ആക്ട്",
    c: "Asiatic Registration Act",
    c_ml: "ഏഷ്യാറ്റിക് രജിസ്ട്രേഷൻ ആക്ട്",
    d: "Government of India Act",
    d_ml: "ഗവൺമെന്റ് ഓഫ് ഇന്ത്യ ആക്ട്",
    correct: "C",
    category: "Satyagraha"
  },
  {
    num: 15,
    q: "Which publication did Gandhi start in South Africa in 1903?",
    q_ml: "1903-ൽ ദക്ഷിണാഫ്രിക്കയിൽ ഗാന്ധിജി ആരംഭിച്ച പ്രസിദ്ധീകരണം ഏതാണ്?",
    a: "Young India",
    a_ml: "യംഗ് ഇന്ത്യ",
    b: "Indian Opinion",
    b_ml: "ഇന്ത്യൻ ഒപ്പീനിയൻ",
    c: "Harijan",
    c_ml: "ഹരിജൻ",
    d: "Navajivan",
    d_ml: "നവജീവൻ",
    correct: "B",
    category: "Publications"
  },
  {
    num: 16,
    q: "The Phoenix Settlement was established in:",
    q_ml: "ഫീനിക്സ് സെറ്റിൽമെന്റ് സ്ഥാപിക്കപ്പെട്ട വർഷം ഏതാണ്?",
    a: "1903",
    a_ml: "1903",
    b: "1904",
    b_ml: "1904",
    c: "1906",
    c_ml: "1906",
    d: "1909",
    d_ml: "1909",
    correct: "B",
    category: "Ashrams & Settlements"
  },
  {
    num: 17,
    q: "The Tolstoy Farm was established near:",
    q_ml: "ടോൾസ്റ്റോയ് ഫാം എവിടെയാണ് സ്ഥാപിക്കപ്പെട്ടത്?",
    a: "Durban",
    a_ml: "ഡർബൻ",
    b: "Johannesburg",
    b_ml: "ജോഹന്നാസ്ബർഗ്",
    c: "Porbandar",
    c_ml: "പോർബന്ദർ",
    d: "Ahmedabad",
    d_ml: "അഹമ്മദാബാദ്",
    correct: "B",
    category: "Ashrams & Settlements"
  },
  {
    num: 18,
    q: "On what date did Gandhi return to India in 1915?",
    q_ml: "1915-ൽ ഗാന്ധിജി ഇന്ത്യയിലേക്ക് മടങ്ങിയെത്തിയ തീയതി ഏതാണ്?",
    a: "2 October",
    a_ml: "ഒക്ടോബർ 2",
    b: "30 January",
    b_ml: "ജനുവരി 30",
    c: "9 January",
    c_ml: "ജനുവരി 9",
    d: "12 March",
    d_ml: "മാർച്ച് 12",
    correct: "C",
    category: "Return to India"
  },
  {
    num: 19,
    q: "Gandhi's return to India is associated with which observance mentioned in the module?",
    q_ml: "ഗാന്ധിജിയുടെ ഇന്ത്യയിലേക്കുള്ള തിരിച്ചുവരവ് ഏത് ദിനാചരണവുമായി ബന്ധപ്പെട്ടിരിക്കുന്നു?",
    a: "Republic Day",
    a_ml: "റിപ്പബ്ലിക് ദിനം",
    b: "Pravasi Bharatiya Divas",
    b_ml: "പ്രവാസി ഭാരതീയ ദിവസ്",
    c: "Independence Day",
    c_ml: "സ്വാതന്ത്ര്യദിനം",
    d: "Gandhi Jayanti",
    d_ml: "ഗാന്ധി ജയന്തി",
    correct: "B",
    category: "Key Observances"
  },
  {
    num: 20,
    q: "Who was Gandhi's political guru?",
    q_ml: "ഗാന്ധിജിയുടെ രാഷ്ട്രീയ ഗുരു ആരായിരുന്നു?",
    a: "Jawaharlal Nehru",
    a_ml: "ജവഹർലാൽ നെഹ്റു",
    b: "Gopal Krishna Gokhale",
    b_ml: "ഗോപാലകൃഷ്ണ ഗോഖലെ",
    c: "Rajendra Prasad",
    c_ml: "രാജേന്ദ്ര പ്രസാദ്",
    d: "C. F. Andrews",
    d_ml: "സി. എഫ്. ആൻഡ്രൂസ്",
    correct: "B",
    category: "Mentors & Leaders"
  },
  {
    num: 21,
    q: "Which ashram did Gandhi establish in Ahmedabad in 1915?",
    q_ml: "1915-ൽ അഹമ്മദാബാദിൽ ഗാന്ധിജി സ്ഥാപിച്ച ആശ്രമം ഏതാണ്?",
    a: "Sabarmati Ashram",
    a_ml: "സബർമതി ആശ്രമം",
    b: "Kochrab Ashram",
    b_ml: "കൊച്ചരബ് ആശ്രമം",
    c: "Phoenix Settlement",
    c_ml: "ഫീനിക്സ് സെറ്റിൽമെന്റ്",
    d: "Tolstoy Farm",
    d_ml: "ടോൾസ്റ്റോയ് ഫാം",
    correct: "B",
    category: "Ashrams"
  },
  {
    num: 22,
    q: "Kochrab Ashram was later shifted to the banks of the:",
    q_ml: "കൊച്ചരബ് ആശ്രമം പിന്നീട് ഏത് നദിയുടെ തീരത്തേക്കാണ് മാറ്റിയത്?",
    a: "Ganges",
    a_ml: "ഗംഗ",
    b: "Yamuna",
    b_ml: "യമുന",
    c: "Sabarmati",
    c_ml: "സബർമതി",
    d: "Narmada",
    d_ml: "നർമ്മദ",
    correct: "C",
    category: "Ashrams"
  },
  {
    num: 23,
    q: "Which was Gandhi's first Satyagraha in India according to the module?",
    q_ml: "പഠനസഹായി പ്രകാരം ഇന്ത്യയിൽ ഗാന്ധിജിയുടെ ആദ്യ സത്യാഗ്രഹം ഏതാണ്?",
    a: "Kheda",
    a_ml: "ഖേദ",
    b: "Ahmedabad",
    b_ml: "അഹമ്മദാബാദ്",
    c: "Champaran",
    c_ml: "ചമ്പാരൻ",
    d: "Rowlatt",
    d_ml: "റൗലറ്റ്",
    correct: "C",
    category: "Early Satyagrahas in India"
  },
  {
    num: 24,
    q: "The Champaran Satyagraha was associated with:",
    q_ml: "ചമ്പാരൻ സത്യാഗ്രഹം ആരുമായി ബന്ധപ്പെട്ടിരിക്കുന്നു?",
    a: "Indigo farmers",
    a_ml: "നീലം കർഷകർ",
    b: "Mill workers",
    b_ml: "മിൽ തൊഴിലാളികൾ",
    c: "Salt workers",
    c_ml: "ഉപ്പ് തൊഴിലാളികൾ",
    d: "Textile merchants",
    d_ml: "തുണി വ്യാപാരികൾ",
    correct: "A",
    category: "Early Satyagrahas in India"
  },
  {
    num: 25,
    q: "Who invited Gandhi to Champaran?",
    q_ml: "ഗാന്ധിജിയെ ചമ്പാരനിലേക്ക് ക്ഷണിച്ചത് ആരാണ്?",
    a: "Rajendra Prasad",
    a_ml: "രാജേന്ദ്ര പ്രസാദ്",
    b: "Rajkumar Shukla",
    b_ml: "രാജ്കുമാർ ശുക്ല",
    c: "Vallabhbhai Patel",
    c_ml: "വല്ലഭ്ഭായ് പട്ടേൽ",
    d: "Gopal Krishna Gokhale",
    d_ml: "ഗോപാലകൃഷ്ണ ഗോഖലെ",
    correct: "B",
    category: "Early Satyagrahas in India"
  },
  {
    num: 26,
    q: "Gandhi's first hunger strike in India mentioned in the module took place during:",
    q_ml: "ഇന്ത്യയിൽ ഗാന്ധിജിയുടെ ആദ്യ നിരാഹാര സമരം ഏത് പ്രക്ഷോഭത്തിലാണ് നടന്നത്?",
    a: "Kheda Satyagraha",
    a_ml: "ഖേദ സത്യാഗ്രഹം",
    b: "Ahmedabad Mill Strike",
    b_ml: "അഹമ്മദാബാദ് മിൽ സമരം",
    c: "Champaran Satyagraha",
    c_ml: "ചമ്പാരൻ സത്യാഗ്രഹം",
    d: "Rowlatt Satyagraha",
    d_ml: "റൗലറ്റ് സത്യാഗ്രഹം",
    correct: "B",
    category: "Early Satyagrahas in India"
  },
  {
    num: 27,
    q: "The Kheda Satyagraha was mainly connected with demands for:",
    q_ml: "ഖേദ സത്യാഗ്രഹം പ്രധാനമായും ഏത് ആവശ്യവുമായി ബന്ധപ്പെട്ടിരുന്നു?",
    a: "Salt tax abolition",
    a_ml: "ഉപ്പ് നികുതി റദ്ദാക്കൽ",
    b: "Tax relief for affected farmers",
    b_ml: "ദുരിതബാധിതരായ കർഷകർക്കുള്ള നികുതി ഇളവ്",
    c: "Factory wage increases",
    c_ml: "ഫാക്ടറി വേതന വർദ്ധനവ്",
    d: "Separate electorates",
    d_ml: "പ്രത്യേക തിരഞ്ഞെടുപ്പ് മണ്ഡലങ്ങൾ",
    correct: "B",
    category: "Early Satyagrahas in India"
  },
  {
    num: 28,
    q: "Which leader's leadership qualities became evident during the Kheda Satyagraha?",
    q_ml: "ഖേദ സത്യാഗ്രഹത്തിലൂടെ പ്രകടമായ നേതൃപാടവം ആരുടേതായിരുന്നു?",
    a: "Vallabhbhai Patel",
    a_ml: "വല്ലഭ്ഭായ് പട്ടേൽ",
    b: "Rajendra Prasad",
    b_ml: "രാജേന്ദ്ര പ്രസാദ്",
    c: "C. F. Andrews",
    c_ml: "സി. എഫ്. ആൻഡ്രൂസ്",
    d: "Mahadev Desai",
    d_ml: "മഹാദേവ് ദേശായി",
    correct: "A",
    category: "Early Satyagrahas in India"
  },
  {
    num: 29,
    q: "Which sequence correctly represents Gandhi's early Indian Satyagrahas?",
    q_ml: "ഗാന്ധിജിയുടെ ആദ്യകാല ഇന്ത്യൻ സത്യാഗ്രഹങ്ങളുടെ ശരിയായ കാലഗണനാ ക്രമം ഏതാണ്?",
    a: "Kheda → Champaran → Ahmedabad",
    a_ml: "ഖേദ → ചമ്പാരൻ → അഹമ്മദാബാദ്",
    b: "Ahmedabad → Kheda → Champaran",
    b_ml: "അഹമ്മദാബാദ് → ഖേദ → ചമ്പാരൻ",
    c: "Champaran → Ahmedabad → Kheda",
    c_ml: "ചമ്പാരൻ → അഹമ്മദാബാദ് → ഖേദ",
    d: "Champaran → Kheda → Ahmedabad",
    d_ml: "ചമ്പാരൻ → ഖേദ → അഹമ്മദാബാദ്",
    correct: "C",
    category: "Chronology"
  },
  {
    num: 30,
    q: "The Rowlatt Satyagraha took place in:",
    q_ml: "റൗലറ്റ് സത്യാഗ്രഹം നടന്ന വർഷം ഏതാണ്?",
    a: "1917",
    a_ml: "1917",
    b: "1919",
    b_ml: "1919",
    c: "1920",
    c_ml: "1920",
    d: "1922",
    d_ml: "1922",
    correct: "B",
    category: "Indian Freedom Movement"
  },
  {
    num: 31,
    q: "The Non-Cooperation Movement began in:",
    q_ml: "നിസ്സഹകരണ പ്രസ്ഥാനം ആരംഭിച്ച വർഷം ഏതാണ്?",
    a: "1919",
    a_ml: "1919",
    b: "1920",
    b_ml: "1920",
    c: "1924",
    c_ml: "1924",
    d: "1930",
    d_ml: "1930",
    correct: "B",
    category: "Non-Cooperation Movement"
  },
  {
    num: 32,
    q: "Which of the following was part of the Non-Cooperation programme described in the module?",
    q_ml: "പഠനസഹായിൽ വിവരിച്ചിട്ടുള്ള നിസ്സഹകരണ പരിപാടിയുടെ ഭാഗമായിരുന്നത് ഏതാണ്?",
    a: "Boycott of government institutions and foreign cloth",
    a_ml: "സർക്കാർ സ്ഥാപനങ്ങളും വിദേശ വസ്ത്രങ്ങളും ബഹിഷ്കരിക്കൽ",
    b: "Armed resistance",
    b_ml: "സായുധ പ്രതിരോധം",
    c: "Tax collection",
    c_ml: "നികുതി പിരിവ്",
    d: "Formation of a separate army",
    d_ml: "പ്രത്യേക സൈന്യം രൂപീകരിക്കൽ",
    correct: "A",
    category: "Non-Cooperation Movement"
  },
  {
    num: 33,
    q: "Which event led Gandhi to withdraw the Non-Cooperation Movement?",
    q_ml: "നിസ്സഹകരണ പ്രസ്ഥാനം പിൻവലിക്കാൻ ഗാന്ധിജിയെ പ്രേരിപ്പിച്ച സംഭവം ഏതാണ്?",
    a: "Jallianwala Bagh",
    a_ml: "ജാലിയൻവാലാബാഗ്",
    b: "Chauri Chaura",
    b_ml: "ചൗരി ചൗര",
    c: "Dandi March",
    c_ml: "ദണ്ഡി യാത്ര",
    d: "Poona Pact",
    d_ml: "പൂന ഉടമ്പടി",
    correct: "B",
    category: "Non-Cooperation Movement"
  },
  {
    num: 34,
    q: "The Chauri Chaura incident occurred in:",
    q_ml: "ചൗരി ചൗര സംഭവം നടന്ന വർഷം ഏതാണ്?",
    a: "1919",
    a_ml: "1919",
    b: "1920",
    b_ml: "1920",
    c: "1922",
    c_ml: "1922",
    d: "1930",
    d_ml: "1930",
    correct: "C",
    category: "Non-Cooperation Movement"
  },
  {
    num: 35,
    q: "The Dandi March began from:",
    q_ml: "ദണ്ഡി യാത്ര ആരംഭിച്ചത് എവിടെ നിന്നാണ്?",
    a: "Kochrab Ashram",
    a_ml: "കൊച്ചരബ് ആശ്രമം",
    b: "Sabarmati Ashram",
    b_ml: "സബർമതി ആശ്രമം",
    c: "Phoenix Settlement",
    c_ml: "ഫീനിക്സ് സെറ്റിൽമെന്റ്",
    d: "Porbandar",
    d_ml: "പോർബന്ദർ",
    correct: "B",
    category: "Civil Disobedience & Dandi March"
  },
  {
    num: 36,
    q: "Approximately how far was the Dandi March according to the module?",
    q_ml: "പഠനസഹായി പ്രകാരം ദണ്ഡി യാത്രയുടെ ഏകദേശ ദൂരം എത്രയായിരുന്നു?",
    a: "185 km",
    a_ml: "185 കി.മീ",
    b: "285 km",
    b_ml: "285 കി.മീ",
    c: "385 km",
    c_ml: "385 കി.മീ",
    d: "485 km",
    d_ml: "485 കി.മീ",
    correct: "C",
    category: "Civil Disobedience & Dandi March"
  },
  {
    num: 37,
    q: "How many volunteers accompanied Gandhi in the Dandi March?",
    q_ml: "ദണ്ഡി യാത്രയിൽ ഗാന്ധിജിയെ അനുഗമിച്ച സന്നദ്ധപ്രവർത്തകർ എത്ര പേരായിരുന്നു?",
    a: "58",
    a_ml: "58",
    b: "68",
    b_ml: "68",
    c: "78",
    c_ml: "78",
    d: "88",
    d_ml: "88",
    correct: "C",
    category: "Civil Disobedience & Dandi March"
  },
  {
    num: 38,
    q: "The Gandhi-Irwin Pact was signed in:",
    q_ml: "ഗാന്ധി-ഇർവിൻ കരാർ ഒപ്പിട്ട വർഷം ഏതാണ്?",
    a: "1930",
    a_ml: "1930",
    b: "1931",
    b_ml: "1931",
    c: "1932",
    c_ml: "1932",
    d: "1934",
    d_ml: "1934",
    correct: "B",
    category: "Key Pacts & Agreements"
  },
  {
    num: 39,
    q: "Who was the Viceroy involved in the Gandhi-Irwin Pact?",
    q_ml: "ഗാന്ധി-ഇർവിൻ കരാറിൽ ഉൾപ്പെട്ട വൈസ്രോയി ആരായിരുന്നു?",
    a: "Lord Curzon",
    a_ml: "കഴ്സൺ പ്രഭു",
    b: "Lord Irwin",
    b_ml: "ഇർവിൻ പ്രഭു",
    c: "Lord Mountbatten",
    c_ml: "മൗണ്ട് ബാറ്റൺ പ്രഭു",
    d: "Lord Wavell",
    d_ml: "വേവൽ പ്രഭു",
    correct: "B",
    category: "Key Pacts & Agreements"
  },
  {
    num: 40,
    q: "The Poona Pact was associated with Gandhi and:",
    q_ml: "പൂന കരാർ ഗാന്ധിജിയുമായും മറ്റാരുമായാണ് ബന്ധപ്പെട്ടിരിക്കുന്നത്?",
    a: "Jawaharlal Nehru",
    a_ml: "ജവഹർലാൽ നെഹ്റു",
    b: "B. R. Ambedkar",
    b_ml: "ബി. ആർ. അംബേദ്കർ",
    c: "Rajendra Prasad",
    c_ml: "രാജേന്ദ്ര പ്രസാദ്",
    d: "Vallabhbhai Patel",
    d_ml: "വല്ലഭ്ഭായ് പട്ടേൽ",
    correct: "B",
    category: "Key Pacts & Agreements"
  },
  {
    num: 41,
    q: "The Quit India Movement was launched on:",
    q_ml: "ക്വിറ്റ് ഇന്ത്യാ സമരം ആരംഭിച്ച തീയതി ഏതാണ്?",
    a: "8 August 1942",
    a_ml: "1942 ആഗസ്റ്റ് 8",
    b: "15 August 1942",
    b_ml: "1942 ആഗസ്റ്റ് 15",
    c: "26 January 1942",
    c_ml: "1942 ജനുവരി 26",
    d: "2 October 1942",
    d_ml: "1942 ഒക്ടോബർ 2",
    correct: "A",
    category: "Quit India Movement"
  },
  {
    num: 42,
    q: "Where was the Quit India call given according to the module?",
    q_ml: "പഠനസഹായി പ്രകാരം ക്വിറ്റ് ഇന്ത്യാ ആഹ്വാനം നൽകിയ സ്ഥലം ഏതാണ്?",
    a: "Sabarmati Ashram",
    a_ml: "സബർമതി ആശ്രമം",
    b: "Gowalia Tank Maidan, Bombay",
    b_ml: "ഗോവാലിയ ടാങ്ക് മൈതാനം, ബോംബെ",
    c: "Dandi",
    c_ml: "ദണ്ഡി",
    d: "Rajghat",
    d_ml: "രാജ്ഘട്ട്",
    correct: "B",
    category: "Quit India Movement"
  },
  {
    num: 43,
    q: "Which phrase was Gandhi's famous call during the Quit India Movement?",
    q_ml: "ക്വിറ്റ് ഇന്ത്യാ സമരകാലത്തെ ഗാന്ധിജിയുടെ പ്രശസ്തമായ ആഹ്വാനം ഏതായിരുന്നു?",
    a: "Jai Hind",
    a_ml: "ജയ് ഹിന്ദ്",
    b: "Swaraj is my birthright",
    b_ml: "സ്വരാജ് എന്റെ ജന്മാവകാശമാണ്",
    c: "Do or Die",
    c_ml: "പ്രവർത്തിക്കുക അല്ലെങ്കിൽ മരിക്കുക (Do or Die)",
    d: "Truth is God",
    d_ml: "സത്യമാണ് ദൈവം",
    correct: "C",
    category: "Quit India Movement"
  },
  {
    num: 44,
    q: "What does Gandhi's concept of Swaraj include according to the module?",
    q_ml: "പഠനസഹായി പ്രകാരം ഗാന്ധിജിയുടെ സ്വരാജ് എന്ന സങ്കല്പത്തിൽ ഉൾപ്പെടുന്നത് എന്താണ്?",
    a: "Only freedom from Britain",
    a_ml: "ബ്രിട്ടനിൽ നിന്നുള്ള സ്വാതന്ത്ര്യം മാത്രം",
    b: "Self-rule and self-control",
    b_ml: "സ്വയംഭരണവും ആത്മനിയന്ത്രണവും",
    c: "Military independence",
    c_ml: "സൈനിക സ്വാതന്ത്ര്യം",
    d: "Economic isolation",
    d_ml: "സാമ്പത്തിക ഒറ്റപ്പെടൽ",
    correct: "B",
    category: "Philosophy & Principles"
  },
  {
    num: 45,
    q: "The idea of Sarvodaya means:",
    q_ml: "സർവ്വോദയം എന്ന ആശയം അർത്ഥമാക്കുന്നത്:",
    a: "Political independence",
    a_ml: "രാഷ്ട്രീയ സ്വാതന്ത്ര്യം",
    b: "Welfare/upliftment of all",
    b_ml: "എല്ലാവരുടെയും ക്ഷേമം / ഉന്നമനം",
    c: "Village administration",
    c_ml: "ഗ്രാമഭരണം",
    d: "Economic boycott",
    d_ml: "സാമ്പത്തിക ബഹിഷ്കരണം",
    correct: "B",
    category: "Philosophy & Principles"
  },
  {
    num: 46,
    q: "The concept of Sarvodaya was inspired by John Ruskin's:",
    q_ml: "സർവ്വോദയം എന്ന ആശയത്തിന് പ്രചോദനമായ ജോൺ റസ്കിന്റെ കൃതി ഏതാണ്?",
    a: "Hind Swaraj",
    a_ml: "ഹിന്ദ് സ്വരാജ്",
    b: "Unto This Last",
    b_ml: "അൺടു ദിസ് ലാസ്റ്റ് (Unto This Last)",
    c: "Key to Health",
    c_ml: "കീ ടു ഹെൽത്ത്",
    d: "Young India",
    d_ml: "യംഗ് ഇന്ത്യ",
    correct: "B",
    category: "Philosophy & Influences"
  },
  {
    num: 47,
    q: "Which book was written by Gandhi in 1909 during a voyage from London to South Africa?",
    q_ml: "1909-ൽ ലണ്ടനിൽ നിന്ന് ദക്ഷിണാഫ്രിക്കയിലേക്കുള്ള യാത്രാവേളയിൽ ഗാന്ധിജി രചിച്ച പുസ്തകം ഏതാണ്?",
    a: "Harijan",
    a_ml: "ഹരിജൻ",
    b: "Hind Swaraj",
    b_ml: "ഹിന്ദ് സ്വരാജ്",
    c: "Key to Health",
    c_ml: "കീ ടു ഹെൽത്ത്",
    d: "Indian Opinion",
    d_ml: "ഇന്ത്യൻ ഒപ്പീനിയൻ",
    correct: "B",
    category: "Literary Works"
  },
  {
    num: 48,
    q: "Which publication was associated with Gandhi from 1933?",
    q_ml: "1933 മുതൽ ഗാന്ധിജിയുമായി ബന്ധപ്പെട്ട പ്രസിദ്ധീകരണം ഏതാണ്?",
    a: "Harijan",
    a_ml: "ഹരിജൻ",
    b: "Young India",
    b_ml: "യംഗ് ഇന്ത്യ",
    c: "Navajivan",
    c_ml: "നവജീവൻ",
    d: "Indian Opinion",
    d_ml: "ഇന്ത്യൻ ഒപ്പീനിയൻ",
    correct: "A",
    category: "Publications"
  },
  {
    num: 49,
    q: "Who was known as the “Kerala Gandhi” according to the module?",
    q_ml: "പഠനസഹായി പ്രകാരം “കേരള ഗാന്ധി” എന്നറിയപ്പെട്ടത് ആരാണ്?",
    a: "K. Kelappan",
    a_ml: "കെ. കേളപ്പൻ",
    b: "A. K. Gopalan",
    b_ml: "എ. കെ. ഗോപാലൻ",
    c: "T. K. Madhavan",
    c_ml: "ടി. കെ. മാധവൻ",
    d: "K. P. Kesava Menon",
    d_ml: "കെ. പി. കേശവമേനോൻ",
    correct: "A",
    category: "Gandhi & Kerala"
  },
  {
    num: 50,
    q: "Which place was the main venue of Kerala's 1930 Salt Satyagraha mentioned in the module?",
    q_ml: "1930-ൽ കേരളത്തിൽ നടന്ന ഉപ്പുസത്യാഗ്രഹത്തിന്റെ പ്രധാന വേദി ഏതാണ്?",
    a: "Vaikom",
    a_ml: "വൈക്കം",
    b: "Kozhikode",
    b_ml: "കോഴിക്കോട്",
    c: "Payyanur",
    c_ml: "പയ്യന്നൂർ",
    d: "Sivagiri",
    d_ml: "ശിവഗിരി",
    correct: "C",
    category: "Gandhi & Kerala"
  }
];

function generateUuid(num) {
  return `00000000-0000-0000-0000-${String(num).padStart(12, '0')}`;
}

const formattedQuestions = rawQuestions.map((q, idx) => ({
  id: generateUuid(q.num),
  question_text: q.q,
  question_text_ml: q.q_ml,
  option_a: q.a,
  option_a_ml: q.a_ml,
  option_b: q.b,
  option_b_ml: q.b_ml,
  option_c: q.c,
  option_c_ml: q.c_ml,
  option_d: q.d,
  option_d_ml: q.d_ml,
  correct_option: q.correct,
  category: q.category,
  difficulty: "MEDIUM",
  explanation: `Answer is option ${q.correct}. Ref: TKFK Gandhi Knowledge Challenge Study Module.`
}));

// 1. Write src/data/questions.ts
const tsContent = `import { Question } from '@/types';\n\nexport const OFFICIAL_50_QUESTIONS: Question[] = ${JSON.stringify(formattedQuestions, null, 2)};\n`;
fs.writeFileSync(path.join(__dirname, '../src/data/questions.ts'), tsContent, 'utf8');
console.log('✅ Successfully wrote src/data/questions.ts with 50 new questions');

// 2. Connect to Supabase and Upsert into questions table
async function seedSupabase() {
  const env = fs.readFileSync('.env.local', 'utf8');
  const envVars = Object.fromEntries(env.split('\n').filter(l => l.includes('=')).map(l => {
    const idx = l.indexOf('=');
    return [l.substring(0, idx).trim(), l.substring(idx + 1).trim()];
  }));

  const supabase = createClient(envVars.NEXT_PUBLIC_SUPABASE_URL, envVars.SUPABASE_SERVICE_ROLE_KEY);

  const rows = formattedQuestions.map(q => ({
    id: q.id,
    question_text: q.question_text,
    option_a: q.option_a,
    option_b: q.option_b,
    option_c: q.option_c,
    option_d: q.option_d,
    correct_option: q.correct_option,
    category: q.category,
    difficulty: q.difficulty,
    explanation: q.explanation
  }));

  console.log('Upserting 50 questions to Supabase questions table...');
  const { data, error } = await supabase
    .from('questions')
    .upsert(rows, { onConflict: 'id' })
    .select();

  if (error) {
    console.error('❌ Supabase Upsert Error:', error);
    process.exit(1);
  }

  console.log(`✅ Successfully upserted ${data ? data.length : 0} questions to Supabase questions table!`);

  // Verify total count in DB
  const { count, error: countErr } = await supabase.from('questions').select('*', { count: 'exact', head: true });
  console.log(`📊 Total questions count in database: ${count}`);
}

seedSupabase().catch(err => {
  console.error('Fatal:', err);
  process.exit(1);
});
